version: '3'

services:
  mysql-server:
    image: haakco/mysql80
    expose:
      - "3306"
    hostname:
      mysql-server
    container_name:
      mysql-server
    restart:
      unless-stopped
    volumes:
      - mysql-server-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123
    cap_add:
      - SYS_NICE
    networks:
      app_net:
        ipv4_address: 172.16.238.10
  zabbix-server:
    image: zabbix/zabbix-server-mysql
    ports:
      - '10051:10051'
    hostname:
      zabbix-server
    container_name:
      zabbix-server
    volumes:
      - zabbix-server-config:/etc/zabbix
    restart:
      unless-stopped
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123
    depends_on:
      - mysql-server
    networks:
      app_net:
        ipv4_address: 172.16.238.11
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql
    ports:
      - '8080:8080'
    hostname:
      zabbix-web
    container_name:
      zabbix-web
    volumes:
      - zabbix-web-config:/etc/zabbix
    restart:
      unless-stopped
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123
      - ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - mysql-server
      - zabbix-server
    networks:
      app_net:
        ipv4_address: 172.16.238.12
  zabbix-agent:
    image: zabbix/zabbix-agent
    ports:
      - '10050:10050'
    hostname:
      zabbix-agent
    container_name:
      zabbix-agent
    restart:
      unless-stopped
    volumes:
      - zabbix-agent-config:/etc/zabbix
    environment:
      - ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - zabbix-server
    networks:
      app_net:
        ipv4_address: 172.16.238.13

volumes:
  mysql-server-data:
  zabbix-server-config:
  zabbix-web-config:
  zabbix-agent-config:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
